sudo: false

language: elixir
elixir:
  - 1.3.0
otp_release:
  - 19.0

addons:
  apt:
    packages:
      - build-essential
      - dbus
      - python3
      - python3-gi
      - python3-dbus
      - python3-pycurl
      - libglib2.0-0
