sudo: false

language: elixir
elixir:
  - 1.3.0
otp_release:
  - 19.0

addons:
  apt:
    packages:
      - xvfb
      - build-essential
      - dbus
      - python3
      - python3-gi
      - python3-dbus
      - python3-pycurl
      - libglib2.0-0

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - mix local.hex --force
  - mix deps.get
